version: '3.6'
services:

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 127.0.0.1:8086:8086
    env_file:
      - 'env.influxdb'
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:6.6.2
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - 'env.grafana'
    volumes:
      - grafana_data:/var/lib/grafana
      # files in this volume will configure the influxdb datasource in grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on: 
      - influxdb
    restart: unless-stopped

volumes:
  grafana_data: {}
  influxdb_data: {}
